### ISSUE TITLE
Not all featured giveaways displaying on Wishlist

### ISSUE THREAD

**Issue by FirstDagger** [nandee95/Extended_Steamgifts#22]
On my Wishlist not all featured giveaways with a high number of items are displaying with Extended Steamgifts on

Steamgifts Wishlist page without ESG
![2016-10-13_13-01-28](https://cloud.githubusercontent.com/assets/8125998/19346805/9d19a396-9145-11e6-8b16-29daed103ab7.png)

Steamgifts Wishlist page with ESG
![2016-10-13_13-01-50](https://cloud.githubusercontent.com/assets/8125998/19346804/9d1848a2-9145-11e6-83cc-10d668ec9f54.png)

My Settings
![2016-10-13_13-03-04](https://cloud.githubusercontent.com/assets/8125998/19346803/9d16b78a-9145-11e6-8685-b9e47e8a7943.png)

**Comment by nandee95** [comment]
It has to be something else. ESG not filtering the pinned giveaways at all.
