### ISSUE TITLE
Gray out joined giveaways

### ISSUE THREAD

**Issue by nhahtdh** [nandee95/Extended_Steamgifts#26]
Would you please gray out joined giveaway like how the site is currently implemented? It helps me tell at a glance that I have already joined the giveaway. The button is not as obvious.

**Comment by nandee95** [comment]
I'm not going to change it. But there is a workaround for you:
https://www.steamgifts.com/discussion/qbPEr/userscript-extended-steamgifts-2310-classes-fixed/search?page=10#lXNsIo3
