### ISSUE TITLE
Steam store widget

### ISSUE THREAD

**Issue by Simvol8** [nandee95/Extended_Steamgifts#27]
Is it possible to turn off store widget without turning off another embedded comment features?
In topics like this https://www.steamgifts.com/discussion/JqvGH/best-deals-of-the-halloween-steam-sale-update-deals-packs-passes-stores it takes ages to load the page. And the page freezes until it is fully loaded

**Comment by nandee95** [comment]
My setup don't have any issue loading this page using the latest Opera and Chrome. The script is not under active development and I cant really do anything about it to make it more performant. If I wish to add it to the settings i should remake the settings entirely which is not an option either.
