### ISSUE TITLE
Some security findings

### ISSUE THREAD

**Issue by muhammadantoun** [nandee95/Extended_Steamgifts#31]
Hi Team,

Don’t you just hate it when someone includes your open source project, only to run some scanning tools and come back with issues?  Yea we do too.

So we’ve been running lots of security scans on open source projects, including yours, through some automation we built.  Don’t worry, it took less than a few minutes to run the scans and auto-generate the report.

Wasn’t sure how to send it to you, so we’ve stuck them up at https://source-security.co.uk/da1f130c-c37c-4d4c-82ce-e9776d371d9b/ so you can see if anything needs handled.  Feel free to re-run the security scanning anytime you like, it’s free for open source.

Best of luck,

Muhammad

**Comment by nandee95** [comment]
Hi

Thank you for the effort. I went through the report and don't think anyone should be concerned about Extended Steamgift's security. This extension is only crafting with the data provided through the browser's authentication, no personal information or tokens are stored or sent. If the script runs on an unintended page I would call It a bug not a security issue.

If you are one of the developers of this tool I would recommend reducing the duplicated pages near the end It was hard to find something I haven't seen before.
