### ISSUE TITLE
Cannot hide giveaway for an item after entering any giveaway

### ISSUE THREAD

**Issue by FirstDagger** [nandee95/Extended_Steamgifts#7]
Enter any giveaway using the green +Enter button
Try to hide any giveaway item using the crossed out eye icon
"Would you like to hide all giveaways for <item>" does NOT open and page cannot be interacted with

This become very annoying if entering giveaway further down the list and trying to hide any giveaway further down the list

**Comment by JoiNNN** [comment]
@FirstDagger I just tested it and works as expected. Can you test again and make sure your version is up-to-date and also disable any other extension or user-script that might interfere with the script.

**Comment by FirstDagger** [comment]
@JoiNNN
No other extensions running, Ublock Origin disabled, Greasemonkey 3.7 and Script version 2.0.3
Firefox 46.0a2
![2016-03-09_09-16-06 image 1](https://cloud.githubusercontent.com/assets/8125998/13629185/a48c3b4e-e5d7-11e5-993f-96b9dba3cdd5.png)
Running these options
Still not working

**Comment by JoiNNN** [comment]
OK, it seems to be cause by the "Hide entered giveaways" option. I'm looking into it, you can disable the option until a fix is provided.

**Edit:** Fixed, if you want to update the script before a new release go **[here](https://github.com/JoiNNN/Extended_Steamgifts/blob/2e3d47e2ca1d8842c13146368d25331a83441d17/Extended_Steamgifts.user.js)** and click the "**Raw**" button, a TamperMonkey prompt page to reinstall the script should appear, click "**Reinstall**".

**Comment by FirstDagger** [comment]
Works like a charm, thank you very very much and keep up the good work on this awesome script.
